'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const {Collection,ChannelType}=require('discord.js');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vnl-giveaway-'));
process.env.DB_PATH=path.join(dir,'test.sqlite');
const store=require('../utils/giveawayStore');
const system=require('../utils/giveawaySystem');
const {getDb}=require('../utils/database');
const users=['11111111111111111','22222222222222222','33333333333333333','44444444444444444'];
const messages=new Map(),sent=[];
let canSend=true, failMembers=false, failEdit=false, failNotice=false, counter=0;
const members=new Map(users.map(id=>[id,{id,user:{bot:false},roles:{cache:new Collection([['777',{}]])}}]));
const channel={id:'333',guildId:'111',type:ChannelType.GuildText,permissionsFor:()=>({has:()=>canSend}),messages:{fetch:async id=>{
  if (!messages.has(id)) throw new Error('Missing message'); return messages.get(id);
}},send:async payload=>{
  if(failNotice && payload.content) throw new Error('network');
  const message={id:String(++counter),author:{id:'999'},payload,edit:async next=>{if(failEdit)throw new Error('network');message.payload=next;}};
  Object.defineProperty(message,'components',{get:()=>(message.payload.components || []).map(r=>({components:r.toJSON().components.map(c=>({customId:c.custom_id}))}))});
  messages.set(message.id,message);sent.push(payload);return message;
}};
const guild={id:'111',channels:{fetch:async id=>id==='333'?channel:null},roles:{fetch:async id=>id==='777'?{id}:null},members:{me:{},fetch:async value=>{
  if(failMembers)throw new Error('Temporary REST failure');
  const id=typeof value==='string'?value:value.user;
  if(!members.has(id)){const error=new Error('Unknown Member');error.code=10007;throw error;}
  return members.get(id);
}}};
const input={prize:'Discord Nitro',description:'Cảm ơn cộng đồng!',duration:'5m',winners:2,channelId:'333',requiredRole:'777'};
async function join(row,id,changes={}) {
  const interaction={customId:`giveaway:join:${row.id}`,guildId:'111',channelId:'333',guild,user:{id,bot:false},client:{user:{id:'999'}},message:messages.get(row.message_id),inGuild:()=>true,deferReply:async()=>{},editReply:async value=>{interaction.result=value;},...changes};
  await system.handleButton(interaction);return interaction.result?.content || interaction.result;
}
async function main(){
  assert.equal(system.duration('2h'),7200000);
  for(const value of ['0m','4m','31d','-5m','1.5h','Infinityh','5'])assert.throws(()=>system.duration(value));
  assert.equal(new Set(system.sample([...users,users[0]],20)).size,4);
  assert(!system.sample(users,20,[users[0]]).includes(users[0]));
  await assert.rejects(system.create(guild,users[0],{...input,winners:21}));
  await assert.rejects(system.create(guild,users[0],{...input,channelId:'other'}));
  canSend=false;await assert.rejects(system.create(guild,users[0],input));canSend=true;
  const preview=await system.create(guild,users[0],input,true);
  assert.equal(store.get(preview.id),undefined);
  assert.equal(sent.at(-1).components[0].toJSON().components[0].disabled,true);
  assert.deepEqual(sent.at(-1).allowedMentions,{parse:[]});
  const created=await system.create(guild,users[0],input);
  let row=store.get(created.id);
  assert.equal(row.status,'active');
  await join(row,users[0]);assert.equal(store.count(row.id),1);
  await join(row,users[0]);assert.equal(store.count(row.id),0);
  await join(row,users[0]);
  await join(row,users[1]);
  members.get(users[2]).roles.cache.clear();
  assert.match(await join(row,users[2]),/cần role/);assert.equal(store.count(row.id),2);
  assert.match(await join(row,users[3],{guildId:'other'}),/không có/);
  assert.match(await join(row,users[3],{message:{id:'fake',author:{id:'999'}}}),/không có/);
  await join(row,users[3]);
  const child=spawnSync(process.execPath,['-e',`process.env.DB_PATH=${JSON.stringify(process.env.DB_PATH)};const s=require('./utils/giveawayStore');if(s.count('${row.id}')!==3||s.get('${row.id}').status!=='active')process.exit(1);`],{cwd:process.cwd(),encoding:'utf8'});
  assert.equal(child.status,0,child.stderr);
  await assert.rejects(system.act({...guild,id:'other'},row.id,'end'));
  failMembers=true;await assert.rejects(system.act(guild,row.id,'end'));assert.equal(store.get(row.id).status,'active');failMembers=false;
  members.delete(users[3]);members.get(users[1]).roles.cache.clear();
  const ended=await system.act(guild,row.id,'end');
  assert.deepEqual(JSON.parse(ended.winners),[users[0]]);
  assert.equal(ended.notice_state,'sent');
  assert.deepEqual(sent.at(-1).allowedMentions,{parse:[],users:[users[0]]});
  assert.match(sent.at(-1).content,/Chúc mừng/);
  assert.equal(messages.get(row.message_id).payload.components.length,0);
  assert.match(await join(row,users[0]),/đóng/);
  await assert.rejects(system.act(guild,row.id,'end'));
  await assert.rejects(system.act(guild,row.id,'reroll'));
  members.get(users[1]).roles.cache.set('777',{});
  const rerolled=await system.act(guild,row.id,'reroll');assert.deepEqual(JSON.parse(rerolled.winners),[users[1]]);assert.equal(rerolled.round,2);
  const cancelled=await system.create(guild,users[0],input);await join(store.get(cancelled.id),users[0]);
  await system.act(guild,cancelled.id,'cancel');assert.equal(store.get(cancelled.id).status,'cancelled');
  await assert.rejects(system.act(guild,cancelled.id,'reroll'));
  const recovery=await system.create(guild,users[0],input);await join(store.get(recovery.id),users[0]);
  getDb().prepare('UPDATE giveaways SET ends_at = 0 WHERE id = ?').run(recovery.id);
  failEdit=true;await system.tick({guilds:{cache:new Collection([['111',guild]])}});
  assert.equal(store.get(recovery.id).status,'ended');assert.equal(store.get(recovery.id).updated,0);
  failEdit=false;store.patch(recovery.id,{retry_at:0});
  const winnersBefore=store.get(recovery.id).winners;
  await system.tick({guilds:{cache:new Collection([['111',guild]])}});
  assert.equal(store.get(recovery.id).winners,winnersBefore);assert.equal(store.get(recovery.id).updated,1);
  const sentBefore=sent.length;await system.tick({guilds:{cache:new Collection([['111',guild]])}});assert.equal(sent.length,sentBefore);
  const uncertain=await system.create(guild,users[0],input);await join(store.get(uncertain.id),users[0]);
  failNotice=true;await system.act(guild,uncertain.id,'end');failNotice=false;
  assert.equal(store.get(uncertain.id).notice_state,'uncertain');
  const noDuplicate=sent.length;await system.tick({guilds:{cache:new Collection([['111',guild]])}});assert.equal(sent.length,noDuplicate);
  store.patch(uncertain.id,{notice_state:'sending'});store.recoverNotices();assert.equal(store.get(uncertain.id).notice_state,'uncertain');
  const draft=await system.create(guild,users[0],input);
  store.patch(draft.id,{status:'draft',message_id:null});
  getDb().prepare('UPDATE giveaways SET created_at=0 WHERE id=?').run(draft.id);
  const originalFetch=channel.messages.fetch;
  channel.messages.fetch=async target=>typeof target==='object'?new Collection(messages):originalFetch(target);
  await system.tick({user:{id:'999'},guilds:{cache:new Collection([['111',guild]])}});
  assert.equal(store.get(draft.id).status,'active');assert.equal(store.get(draft.id).message_id,draft.messageUrl.split('/').at(-1));
  channel.messages.fetch=originalFetch;
  const restored=spawnSync(process.execPath,['-e',`process.env.DB_PATH=${JSON.stringify(process.env.DB_PATH)};const s=require('./utils/giveawayStore');const r=s.get('${recovery.id}');if(r.status!=='ended'||r.winners!==${JSON.stringify(winnersBefore)})process.exit(1);`],{cwd:process.cwd(),encoding:'utf8'});
  assert.equal(restored.status,0,restored.stderr);
  const commands=require('../utils/loadCommands').loadCommands();assert(commands.has('giveaway'));assert.equal(commands.get('giveaway').data.toJSON().options.length,5);
  console.log('PASS giveaway: persistence across processes, join/withdraw, guild/message isolation, eligibility, unbiased unique selection, cancel/reroll, recovery without redrawing, winner-only pings, preview, slash registration.');
}
main().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{getDb().close();fs.rmSync(dir,{recursive:true,force:true});});
